# Build everything in first stage
FROM python:3.8-alpine as base

FROM base as builder

RUN mkdir /install
WORKDIR /install

COPY server/requirements.txt /install

# Build MySQL library
RUN apk update 
RUN apk add gcc python3-dev musl-dev mariadb-connector-c-dev mysql-client

# Requirements
RUN pip install --install-option="--prefix=/install" -r requirements.txt

# Real image
FROM base

WORKDIR /container

# Copy in build from previous stage
COPY --from=builder /install /usr/local
COPY server .

# Docker specific environment vars
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Install only the MySQL stuff we need
RUN apk update
RUN apk add mariadb-connector-c-dev

# Run server
ENV INTERNAL_PORT 6969
EXPOSE $INTERNAL_PORT
ENTRYPOINT ./run.sh $INTERNAL_PORT

