# Frontend
FROM node:10 as builder
WORKDIR /npm
COPY ui/ .
RUN npm ci --only=production
RUN npm run build

# Build actual nginx image
FROM nginx:stable-alpine

# Copy in npm artifacts from previous iamge
COPY --from=builder /npm/dist/ /usr/share/nginx/html

COPY deployment/inner_nginx.conf /etc/nginx/conf.d/default.conf
