# Build image
FROM python:3.8-alpine

RUN mkdir /container

ADD server/requirements.txt /container

# Set up project directory
WORKDIR /container

# MySQL
RUN apk update 
RUN apk add gcc python3-dev musl-dev mariadb-connector-c-dev mysql-client

# Docker specific environment vars
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

ENV INTERNAL_PORT 6969

COPY server/ .

# Requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Clean up
RUN apk del gcc python3-dev musl-dev

# Run server
EXPOSE $INTERNAL_PORT
ENTRYPOINT ./run.sh $INTERNAL_PORT

