#!/bin/sh

MIGRATIONS_DIRECTORY='server/amaranta_candles/migrations'
UNTRACKED_MIGRATIONS="$(git ls-files --exclude-standard --others -- $MIGRATIONS_DIRECTORIES | egrep '(.*)[.]py$')"

echo "Running makemigrations"
cd server
yes | deployment_mode=dev allowed_hosts=1 secret_key=1 sql_engine='django.db.backends.sqlite3' sql_database=fake.sqlite sql_host=1 sql_user=1 sql_password=1 sql_port=1 ui_username=1 ui_email=1 ui_password=1 pipenv run python manage.py makemigrations amaranta_candles
rm fake.sqlite
cd ..
  
if test -z "$UNTRACKED_MIGRATIONS"; then
    # If there are no untracked .py files in the migrations directory, do nothing, allow commit.
    true;
else
    # If there are untracked files in the migrations directory print a warning message.
    echo "Warning -- Untracked files in the migrations directory"
    echo 'The commit may be forced with "git commit --no-verify"'
    echo 
    echo "$UNTRACKED_MIGRATIONS"
    exit 1
fi
