#!/bin/sh

MIGRATIONS_DIRECTORY='server/amaranta_candles/migrations'
UNTRACKED_MIGRATIONS="$(git ls-files --exclude-standard --others -- $MIGRATIONS_DIRECTORIES | egrep '(.*)[.]py$')"

echo "Running makemigrations"
cd server
./makemigrations.sh
cd ..
  
if test -z "$UNTRACKED_MIGRATIONS"; then
    # If there are no untracked .py files in the migrations directory, do nothing, allow commit.
    true;
else
    # If there are untracked files in the migrations directory print a warning message.
    echo "Warning -- Untracked files in the migrations directory"
    echo 'The commit may be forced with "git commit --no-verify"'
    echo 
    echo "$UNTRACKED_MIGRATIONS"
    exit 1
fi
