# This is a basic workflow to help you get started with Actions

name: Build server and ui images

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  delete_old_versions:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'amaranta_candles_server'
          num-old-versions-to-delete: 50
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'amaranta_candles_ui'
          num-old-versions-to-delete: 50

  remove_old_artifacts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        age: '1 day'
        skip-tags: true
    needs:
     [delete_old_versions]
    
  build_server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: banool/gp-docker-action@1.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: amaranta_candles_server # Provide only Docker image name, tag will be automatically set to latest
        dockerfile: Dockerfile_server
    needs:
      [remove_old_artifacts, delete_old_versions]

  build_ui:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: banool/gp-docker-action@1.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: amaranta_candles_ui # Provide only Docker image name, tag will be automatically set to latest
        dockerfile: Dockerfile_ui
    needs:
      [remove_old_artifacts, delete_old_versions]
